[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "threebody"
version = "0.1.0"
dependencies = [
    "numpy",
    "matplotlib",
    "numba",
    "pygame",
    "pygame_gui",
]
